# Generated by Django 2.0.5 on 2018-05-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cablesite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CableSite',
            new_name='Cable',
        ),
    ]
